<?php
/**
 * Language labels for database tables/fields belonging to extension "ch_trip"
 *
 * This file is detected by the translation tool.
 */

$LOCAL_LANG = Array (
	'default' => Array (
		'tt_content.list_type_pi1' => 'Trip - Travel Information Presenter',	
		
		'tx_chtrip_hotel' => 'Trip: Hotel',	
		'tx_chtrip_hotel.title' => 'Hotel',	
		'tx_chtrip_hotel.location' => 'Address',	
		'tx_chtrip_hotel.id_code' => 'ID/Code',	
		'tx_chtrip_hotel.postcode' => 'Postcode',	
		'tx_chtrip_hotel.weathercode' => 'Weathercode',	
		'tx_chtrip_hotel.specialoffer' => 'Special offer',	
		'tx_chtrip_hotel.room' => 'Room',	
		'tx_chtrip_hotel.teaser' => 'Teaser',	
		'tx_chtrip_hotel.description' => 'Description',	
		'tx_chtrip_hotel.pictures' => 'Pictures',	
		'tx_chtrip_hotel.captions' => 'Captions',	
		'tx_chtrip_hotel.video' => 'Video',
		'tx_chtrip_hotel.map' => 'Map',		
		'tx_chtrip_hotel.related' => 'Related',	
		'tx_chtrip_hotel.location_f04338f846' => 'Region',	
		'tx_chtrip_hotel.hotelproperties' => 'Hotel-Properties',
		'tx_chtrip_hotel.hoteltype' => 'Hotel-Type',
		'tx_chtrip_hotel.metakeywords' => 'Keywords',
		'tx_chtrip_hotel.season' => 'Season',
		'tx_chtrip_hotel.createNewParentCategory' => 'create new parent category',
		'tx_chtrip_hotel.listCategories' => 'list categories',

		'tx_chtrip_region' => 'Trip: Region',	
		'tx_chtrip_region.title' => 'Title',	
		'tx_chtrip_region.parent_uid' => 'Parent-ID',
		'tx_chtrip_region.createNewParentCategory' => 'create new parent category',
		'tx_chtrip_region.listCategories' => 'list categories',
		
		'tx_chtrip_season' => 'Trip: Season',	
		'tx_chtrip_season.title' => 'Title',
		'tx_chtrip_season.from_a1' => 'From',
		'tx_chtrip_season.till_a1' => 'Until',
		'tx_chtrip_season.parent_uid' => 'Parent-ID',

		'tx_chtrip_price' => 'Trip: Price',	
		'tx_chtrip_price.title' => 'Title',
 		'tx_chtrip_price.a_halfboard' => 'Halfboard',
		'tx_chtrip_price.a_baseprice' => 'Baseprice',
		'tx_chtrip_price.season' => 'Season',

		'tx_chtrip_properties' => 'Trip: Properties',	
		'tx_chtrip_properties.title' => 'Title',	
		'tx_chtrip_properties.parent_uid' => 'Parent-ID',	
		'tx_chtrip_properties.createNewParentCategory' => 'create new parent category',
		'tx_chtrip_properties.listCategories' => 'list categories',
		'tx_chtrip_properties.icon' => 'Icon',
		'tx_chtrip_properties.hierarchy' => 'Hierarchy',

		'tx_chtrip_hierarchy' => 'Trip: Hierarchy',	
		'tx_chtrip_hierarchy.title' => 'Titel',	
		'tx_chtrip_hierarchy.parent_uid' => 'Parent-ID',
		'tx_chtrip_hierarchy.createNewParentCategory' => 'create new parent category',
		'tx_chtrip_hierarchy.listCategories' => 'list categories',
		'tx_chtrip_hierarchy.icon' => 'Icon',

		'tx_chtrip_room' => 'Trip: Room',	
		'tx_chtrip_room.title' => 'Title',	
		'tx_chtrip_room.description' => 'Description',	
		'tx_chtrip_room.pictures' => 'Additional pictures',
		'tx_chtrip_room.captions' => 'Captions',		
		'tx_chtrip_room.roomproperties' => 'Room-Properties',		
		'tx_chtrip_room.miscellaneous' => 'Miscellaneous',	
		'tx_chtrip_room.arrivalanddeparture' => 'Arrival and Departure',
		'tx_chtrip_room.special' => 'Special offer',
		
		'tx_chtrip_category' => 'Trip: Category',	
		'tx_chtrip_category.title' => 'Title',	
		'tx_chtrip_category.bookingperiod' => 'Bookingperiod',	
		'tx_chtrip_category.parent_uid' => 'Parent-ID',	
		'tx_chtrip_category.allseason' => 'All-season',	
		'tx_chtrip_category.price' => 'All-season price',	
		'tx_chtrip_category.property' => 'Properties',
		'tx_chtrip_category.halfboard' => 'Halfboard possible, price on application.',		
		'tx_chtrip_category.requestperunit' => 'Request per Unit',	
		'tx_chtrip_category.requestperperson' => 'Request per Person',
		'tx_chtrip_category.seasonprice' => 'Price',
		'tx_chtrip_category.specialoffer' => 'Special offer',

		'tx_chtrip_request' => 'Trip: Request',
		'tx_chtrip_request.salutation' => 'Salutation',		
		'tx_chtrip_request.salutation.I.0' => 'Mrs./Miss',    
		'tx_chtrip_request.salutation.I.1' => 'Mr.',
		'tx_chtrip_request.datefrom' => 'From',   
		'tx_chtrip_request.datetill' => 'Till',
		'tx_chtrip_request.region' => 'Region',    
		'tx_chtrip_request.objtype' => 'Type',    
		'tx_chtrip_request.objname' => 'Name', 
		'tx_chtrip_request.objaccommodation' => 'Accommodation',		
		'tx_chtrip_request.category' => 'Category',           
		'tx_chtrip_request.idcode' => 'ID Code',           
		'tx_chtrip_request.name' => 'Name',        
		'tx_chtrip_request.forename' => 'Forename',    
		'tx_chtrip_request.street' => 'Street',    
		'tx_chtrip_request.where' => 'Where',    
		'tx_chtrip_request.phone' => 'Phone/Fax',    
		'tx_chtrip_request.email' => 'E-Mail',    
		'tx_chtrip_request.name2' => 'Companyname',
        	'tx_chtrip_request.message' => 'Message',
		'tx_chtrip_request.billingaddress.I.0' => 'Private',    
		'tx_chtrip_request.billingaddress.I.1' => 'Business',    
		'tx_chtrip_request.billingaddress' => 'Billing address',    
		'tx_chtrip_request.nl.I.0' => 'Yes',    
		'tx_chtrip_request.nl.I.1' => 'No',    
		'tx_chtrip_request.nl' => 'Newsletter',

		'tt_content.pi_flexform.sheet_general' => 'General Settings',
		'tt_content.pi_flexform.starting_point' => 'Startingpoint',
		
		'ch_trip.pi_flexform.what_to_display' => 'What to display?',
		'ch_trip.pi_flexform.listNo' => 'List (normal)',		
		'ch_trip.pi_flexform.listAlt' => 'List (alternative)',		
		'ch_trip.pi_flexform.spteaser' => 'Special offer (Teaser)',	
		'ch_trip.pi_flexform.splist' => 'Special offer (List)',	
		
		'ch_trip.pi_flexform.menu_template' => 'Menu',
		'ch_trip.pi_flexform.typeSelection' => 'Menu:',		
		
		'ch_trip.pi_flexform.form_template' => 'Formular',
		'ch_trip.pi_flexform.formSelection' => 'Formular:',

		'ch_trip.pi_flexform.sheet_related' => 'Related objects',

		'ch_trip.pi_flexform.sheet_template' => 'Template',
		'ch_trip.pi_flexform.template_file' =>  'Template file',
		
		'ch_trip.pi_flexform.sheet_misc' => 'Other Settings',
		'ch_trip.pi_flexform.specialoffer_at_a_time' => 'Max. special offer',				
		'ch_trip.pi_flexform.results_at_a_time' => 'Results at a time:',
		'ch_trip.pi_flexform.maxPages' => 'Max. Pages:',
		
		'ch_trip.pi_flexform.PIDopUpDisplay' => 'Page ID for the pop-up to display:',
		'ch_trip.pi_flexform.PIDspecialOfferDisplay' => 'Page ID for the special offer to display:',
		'ch_trip.pi_flexform.PIDrelatedObjectDisplay' => 'Page ID for related objects to display:',
		'ch_trip.pi_flexform.PIDnewsletterDisplay' => 'Page ID of the newsletter group:',
		
		'ch_trip.pi_flexform.sheet_email' => 'E-Mail',
		'ch_trip.pi_flexform.subject' => 'Subject',
		'ch_trip.pi_flexform.from_email' => 'From E-Mail (test@xyz.com)',
		'ch_trip.pi_flexform.from_name' => 'From Name',
		'ch_trip.pi_flexform.replyto_email' => 'Reply to E-Mail (test@xyz.com)',
		'ch_trip.pi_flexform.replyto_name' => 'Reply to Name',
		'ch_trip.pi_flexform.organisation' => 'Organisation',
		'ch_trip.pi_flexform.priority' => 'Priority',
		'ch_trip.pi_flexform.label1' => 'High',
		'ch_trip.pi_flexform.label2' => 'Normal',
		'ch_trip.pi_flexform.label3' => 'Low',
		'ch_trip.pi_flexform.returnPath' => 'Return Path (test@xyz.com)',
		'ch_trip.pi_flexform.recipients' =>  'Recipients (comma-separated)',      
		'tt_content.menu_type_pi2' => 'Trip: Sitemap',
		
	),
	'fr' => Array (
		'tt_content.pi_flexform.sheet_general' => 'General FR',
	),
	'en' => Array (
		'tt_content.pi_flexform.sheet_general' => 'General EN',
	),
	'de' => Array (
		'tt_content.list_type_pi1' => 'Trip - Travel Information Presenter',	

		'tx_chtrip_hotel' => 'Trip: Hotel',	
		'tx_chtrip_hotel.title' => 'Hotel',	
		'tx_chtrip_hotel.location' => 'Adresse',	
		'tx_chtrip_hotel.id_code' => 'ID/Code',	
		'tx_chtrip_hotel.postcode' => 'PLZ',	
		'tx_chtrip_hotel.specialoffer' => 'Angebot',	
		'tx_chtrip_hotel.room' => 'Zimmer',	
		'tx_chtrip_hotel.teaser' => 'Teaser',	
		'tx_chtrip_hotel.description' => 'Beschreibung',	
		'tx_chtrip_hotel.pictures' => 'Bilder',	
		'tx_chtrip_hotel.captions' => 'Bildunterschriften',	
		'tx_chtrip_hotel.video' => 'Video',
		'tx_chtrip_hotel.wheremap' => 'Karte',		
		'tx_chtrip_hotel.related' => 'Verwandte Objekte',	
		'tx_chtrip_location.location_f04338f846' => 'Region',	
		'tx_chtrip_hotel.hoteltype' => 'Hotel-Typ',	
		'tx_chtrip_hotel.createNewParentCategory' => 'Datensatz anlegen',
		'tx_chtrip_hotel.listCategories' => 'Datensatz auflisten',
		'tx_chtrip_hotel.hotelproperties' => 'Hotel-Eigenschaften',
        'tx_chtrip_hotel.metakeywords' => 'Keywords',
		'tx_chtrip_hotel.season' => 'Season',

		'tx_chtrip_region' => 'Trip: Region',	
		'tx_chtrip_region.title' => 'Titel',	
		'tx_chtrip_region.parent_uid' => 'Eltern-Datensatz',
		'tx_chtrip_region.createNewParentCategory' => 'Datensatz anlegen',
		'tx_chtrip_region.listCategories' => 'Datensatz auflisten',
		
		'tx_chtrip_season' => 'Trip: Saison',	
		'tx_chtrip_season.title' => 'Titel',
		'tx_chtrip_season.from_a1' => 'Von',
		'tx_chtrip_season.till_a1' => 'Bis',
		'tx_chtrip_season.parent_uid' => 'Eltern-Datensatz',

		'tx_chtrip_price' => 'Trip: Preis',	
		'tx_chtrip_price.title' => 'Title',
 		'tx_chtrip_price.a_halfboard' => 'Halbpension',
		'tx_chtrip_price.a_baseprice' => 'Preis',
		'tx_chtrip_price.season' => 'Season',
		'tx_chtrip_price.specialoffer' => 'Sonderangebot',

		'tx_chtrip_properties' => 'Trip: Eigenschaften',	
		'tx_chtrip_properties.title' => 'Titel',	
		'tx_chtrip_properties.parent_uid' => 'Eltern-Datensatz',
		'tx_chtrip_properties.createNewParentCategory' => 'Datensatz anlegen',
		'tx_chtrip_properties.listCategories' => 'Datensatz auflisten',
		'tx_chtrip_properties.icon' => 'Icon',
		'tx_chtrip_properties.hierarchy' => 'Hierarchy',

		'tx_chtrip_hierarchy' => 'Trip: Hierarchy',	
		'tx_chtrip_hierarchy.title' => 'Titel',	
		'tx_chtrip_hierarchy.parent_uid' => 'Eltern-Datensatz',
		'tx_chtrip_hierarchy.createNewParentCategory' => 'Datensatz anlegen',
		'tx_chtrip_hierarchy.listCategories' => 'Datensatz auflisten',
		'tx_chtrip_hierarchy.icon' => 'Icon',
		
		'tx_chtrip_room' => 'Trip: Zimmer',		
		'tx_chtrip_room.title' => 'Titel',	
		'tx_chtrip_room.description' => 'Zimmerbeschreibung',	
		'tx_chtrip_room.pictures' => 'Zusatzbilder',	
		'tx_chtrip_room.roomproperties' => 'Eigenschaften',		
		'tx_chtrip_room.miscellaneous' => 'Sonstiges',	
		'tx_chtrip_room.arrivalanddeparture' => 'An-und Abreise',	
        'tx_chtrip_room.special' => 'Angebot',
	
		'tx_chtrip_category' => 'Trip: Kategorie',	
		'tx_chtrip_category.title' => 'Titel',	
		'tx_chtrip_category.bookingperiod' => 'Saisonzeiten/Preise',	
		'tx_chtrip_category.parent_uid' => 'Eltern-Datensatz',	
		'tx_chtrip_category.allseason' => 'Ganzjährig',	
		'tx_chtrip_category.price' => 'Preis',	
		'tx_chtrip_category.property' => 'Eigenschaft',	
		'tx_chtrip_category.halfboard' => 'Halbpension möglich, Preise auf Anfrage.',	
		'tx_chtrip_category.requestperunit' => 'Preis pro Einheit & Nacht auf Anfrage möglich (mind. Aufenthalt 2 Nächte)',	
		'tx_chtrip_category.requestperperson' => 'Preis pro Person & Nacht auf Anfrage möglich (mind. Aufenthalt 2 Nächte)',	

		'tx_chtrip_request' => 'Trip: Anfrage',
		'tx_chtrip_request.salutation' => 'Anrede',		
		'tx_chtrip_request.salutation.I.0' => 'Frau',    
		'tx_chtrip_request.salutation.I.1' => 'Herr',        
		'tx_chtrip_request.datefrom' => 'Von',   
		'tx_chtrip_request.datetill' => 'Bis',   	
		'tx_chtrip_request.region' => 'Region',    
		'tx_chtrip_request.objtype' => 'Eigenschaften',    
		'tx_chtrip_request.objname' => 'Name',	
		'tx_chtrip_request.objaccommodation' => 'Objekt',		
		'tx_chtrip_request.category' => 'Kategorie',
		'tx_chtrip_request.idcode' => 'ID Code',        
		'tx_chtrip_request.name' => 'Name',    
		'tx_chtrip_request.forename' => 'Vorname',    
		'tx_chtrip_request.street' => 'Straße',    
		'tx_chtrip_request.where' => 'Ort',    
		'tx_chtrip_request.phone' => 'Tel.',    
		'tx_chtrip_request.fax' => 'Fax',    
		'tx_chtrip_request.email' => 'E-Mail',    
		'tx_chtrip_request.name2' => 'Firmename',
		'tx_chtrip_request.message' => 'Nachricht',
		'tx_chtrip_request.billingaddress.I.0' => 'Privat',    
		'tx_chtrip_request.billingaddress.I.1' => 'Firma',    
		'tx_chtrip_request.billingaddress' => 'Rechnungsanschrift',  
		'tx_chtrip_request.nl.I.0' => 'Ja',    
		'tx_chtrip_request.nl.I.1' => 'Nein',    
		'tx_chtrip_request.nl' => 'Newsletter',

		'tt_content.pi_flexform.sheet_general' => 'Grundeinstellungen',
		'tt_content.pi_flexform.starting_point' => 'Startingpoint',
		
		'ch_trip.pi_flexform.what_to_display' => 'What to display?',
		'ch_trip.pi_flexform.listNo' => 'List (normal)',		
		'ch_trip.pi_flexform.listAlt' => 'List (alternative)',	
		'ch_trip.pi_flexform.spteaser' => 'Special offer (Teaser)',	
		'ch_trip.pi_flexform.splist' => 'Special offer (List)',	
	
		'ch_trip.pi_flexform.menu_template' => 'Menu',
		'ch_trip.pi_flexform.typeSelection' => 'Menu:',

		'ch_trip.pi_flexform.form_template' => 'Formular',
		'ch_trip.pi_flexform.formSelection' => 'Formular:',

		'ch_trip.pi_flexform.sheet_related' => 'Verknüpfte Objekte',

		'ch_trip.pi_flexform.sheet_template' => 'Template',
		'ch_trip.pi_flexform.template_file' =>  'Template File',
		
		'ch_trip.pi_flexform.sheet_misc' => 'Sonstige Einstellungen',
		'ch_trip.pi_flexform.specialoffer_at_a_time' => 'Max. Sonderangebote',		
		'ch_trip.pi_flexform.results_at_a_time' => 'Treffer pro Seite',
		'ch_trip.pi_flexform.maxPages' => 'Max. Seiten',
		
		'ch_trip.pi_flexform.sheet_email' => 'E-Mail',
		'ch_trip.pi_flexform.subject' => 'Betreff',
		'ch_trip.pi_flexform.from_email' => 'Absender E-Mail (test@xyz.com)',	
		'ch_trip.pi_flexform.from_name' => 'From Name',
		'ch_trip.pi_flexform.replyto_email' => 'Reply to E-Mail (test@xyz.com)',
		'ch_trip.pi_flexform.replyto_name' => 'Reply to Name',
		'ch_trip.pi_flexform.organisation' => 'Organisation',
		'ch_trip.pi_flexform.priority' => 'Priority',
		'ch_trip.pi_flexform.label1' => 'High',
		'ch_trip.pi_flexform.label2' => 'Normal',
		'ch_trip.pi_flexform.label3' => 'Low',
		'ch_trip.pi_flexform.returnPath' => 'Return Path',		
		'ch_trip.pi_flexform.recipients' => 'Empfänger (komma-separiert)',

        'tt_content.menu_type_pi2' => 'Trip Sitemap',
	),
);
?>
